#!/bin/bash
export ARB=$(basename "$PWD")
source include.sh # Call the include script so we can use our functions and variables

# welcome and present list of options
echo "Hello, welcome to A Repo Builder, glad you're here! Please choose from the following options so we can get started:"
while true; do
echo "1: New repo"
echo "2: Check and update packages"
echo "3: Rebuild and upload packages"
echo "4: Rebuild repo datebase"
echo "5: Add new packages to existing repo"
echo "6: Remove packages from existing repo"
echo "7: Quit"

read option # read user input
    case $option in
    1)
    source $builddir/add-repo.sh; break;;
    2)
    export $ckupdate="true"
    export $firstbuild="false"
    execbuild
    # find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && sh build.sh" \;
    upload; break;;
    3)
    source $builddir/rebuild.sh; break;;
    4)
    rbdb
    upload; break;;
    5)
    source $builddir/add-pkg.sh; break;;
    6)
    source $builddir/remove-pkg.sh; break;;
    7)
    echo "Thanks for stopping by this script, have a nice day!"; exit;;
    *)
    echo "I can't do that, Dave. Please choose one of the options."; continue;;
esac
done
